Repository Today-s-Gym/backend, pull requests merged in 2023-03, with the labels that each got.

#3 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#4 pull request 템플릿을 생성한다.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 [CHORE] gitignore 수정
  .gitignore
  src/main/resources/application.properties
Labels: infra

#6 [CHORE] build.gradle 수정
  build.gradle
Labels: ⚙infra

#19 [FEATURE] 아바타 정보를 생성한다
  src/main/java/com/todaysgym/todaysgym/avatar/Avatar.java
Labels: 👩‍💻feature

#20 [FEATURE] 카테고리 정보를 생성한다.
  src/main/java/com/todaysgym/todaysgym/category/Category.java
Labels: 👩‍💻feature

#21 #14/record
  build.gradle
  src/main/java/com/todaysgym/todaysgym/TodaysgymApplication.java
  src/main/java/com/todaysgym/todaysgym/config/exception/errorCode/RecordErrorCode.java
  src/main/java/com/todaysgym/todaysgym/member/Member.java
  src/main/java/com/todaysgym/todaysgym/record/Record.java
  src/main/java/com/todaysgym/todaysgym/record/RecordController.java
  src/main/java/com/todaysgym/todaysgym/record/RecordRepository.java
  src/main/java/com/todaysgym/todaysgym/record/RecordService.java
  src/main/java/com/todaysgym/todaysgym/record/dto/RecordGetReq.java
  src/main/java/com/todaysgym/todaysgym/record/photo/RecordPhoto.java
  src/main/java/com/todaysgym/todaysgym/record/photo/RecordPhotoService.java
  src/main/java/com/todaysgym/todaysgym/tag/Tag.java
  src/main/java/com/todaysgym/todaysgym/tag/TagController.java
  src/main/java/com/todaysgym/todaysgym/tag/TagService.java
  src/main/java/com/todaysgym/todaysgym/utils/S3Service.java
  src/main/java/com/todaysgym/todaysgym/utils/dto/getS3Res.java
Labels: 👩‍💻feature
